#!/bin/bash
# DO NOT EDIT THIS FILE

ocamlbuild -pkgs oUnit,yojson,str,ANSITerminal main.byte game.byte
if [[ $? -ne 0 ]]; then
  cat <<EOF
===========================================================
WARNING

Your code currently does not compile.  You will receive
little to no credit for submitting this code. Check the
error messages above carefully to determine what is wrong.
See a consultant for help if you cannot determine what is
wrong.
===========================================================
EOF
  exit 1
fi

cat >checktypes.ml <<EOF
(* DO NOT EDIT THIS FILE *)
let e:exn = Game.Illegal
let check_init_state : Yojson.Basic.json -> Game.state = Game.init_state
let check_max_score : Game.state -> int = Game.max_score
let check_score : Game.state -> int = Game.score
let check_turns : Game.state -> int = Game.turns
let check_current_room_id : Game.state -> string = Game.current_room_id
let check_inv : Game.state -> string list = Game.inv
let check_visited : Game.state -> string list = Game.visited
let check_locations : Game.state -> (string*string) list = Game.locations
let check_do' : string -> Game.state -> Game.state = Game.do'
EOF

if ocamlbuild -pkgs oUnit,yojson,str,ANSITerminal checktypes.byte ; then
  cat <<EOF
===========================================================
Your function names and types look good to me.
Congratulations!
===========================================================
EOF
else
  cat <<EOF
===========================================================
WARNING

Your function names and types look broken to me.  The code
that you submit might not compile on the grader's machine,
leading to heavy penalties.  Please fix your names and
types.  Check the error messages above carefully to
determine what is wrong.  See a consultant for help if you
cannot determine what is wrong.
===========================================================
EOF
fi

